// Auth
export const SET_TOKEN_MUTATION = 'SET_TOKEN_MUTATION'
export const SET_PROFILE_DATA_MUTATION = 'SET_PROFILE_DATA_MUTATION'

// Feed
export const SET_CAN_POST_MUTATION = 'SET_CAN_POST_MUTATION'
export const SET_POST_MUTATION = 'SET_POST_MUTATION'
